// GENERATED FILE — do not edit by hand.
//
// Generated by scripts/generate-api-types.ts from the backend OpenAPI spec.
// Re-run `npm run generate:api-types` after API schema changes.
//
// Import API types in application code via:
//   import type { ApiTypes } from "@/app/types";
//
// See docs/ENVIRONMENT.md and src/app/types/index.ts for usage details.

/* eslint-disable */
// prettier-ignore

/**
 * Placeholder generated types.
 *
 * This file is intentionally minimal. Run `npm run generate:api-types` with
 * the backend running to populate it with the full OpenAPI-derived types.
 *
 * The types below are the canonical shapes derived from the backend schema.
 * Application code (useApi.ts, etc.) imports from here via the
 * `@/app/types` barrel so that a single `generate:api-types` run updates
 * the whole codebase.
 */

export interface paths {}
export interface components {
  schemas: {
    /** Loan resource */
    Loan: {
      id: string;
      amount: number;
      currency: string;
      interestRate: number;
      termDays: number;
      /** @enum {string} */
      status:
        | "pending"
        | "active"
        | "repaid"
        | "defaulted"
        | "liquidated"
        | "approved"
        | "rejected"
        | "open"
        | "overdue";
      borrowerId: string;
      createdAt: string;
    };

    /** Remittance resource */
    Remittance: {
      id: string;
      amount: number;
      fromCurrency: string;
      toCurrency: string;
      recipientAddress: string;
      memo?: string;
      /** @enum {string} */
      status: "pending" | "processing" | "completed" | "failed";
      createdAt: string;
    };

    /** User profile */
    UserProfile: {
      id: string;
      email: string;
      walletAddress?: string;
      kycVerified: boolean;
    };

    /** User wallet balance */
    UserBalance: {
      available: number;
      locked: number;
      currency: string;
    };

    /** Credit score response */
    CreditScoreResponse: {
      success: boolean;
      userId: string;
      score: number;
      band: string;
    };

    /** Pool statistics */
    PoolStats: {
      totalDeposits: number;
      totalOutstanding: number;
      utilizationRate: number;
      apy: number;
      activeLoansCount: number;
      poolTokenAddress?: string;
      withdrawalCooldownLedgers?: number;
    };

    /** Depositor portfolio */
    DepositorPortfolio: {
      address: string;
      depositAmount: number;
      sharePercent: number;
      estimatedYield: number;
      apy: number;
      firstDepositAt: string | null;
      lastDepositAt?: string | null;
    };

    /** Notification */
    AppNotification: {
      id: number;
      userId: string;
      /** @enum {string} */
      type:
        | "loan_approved"
        | "repayment_due"
        | "repayment_confirmed"
        | "loan_defaulted"
        | "score_changed";
      title: string;
      message: string;
      loanId?: number;
      read: boolean;
      createdAt: string;
    };

    /** Auth session */
    AuthSession: {
      publicKey?: string;
      /** @enum {string} */
      role?: "admin" | "borrower" | "lender";
      scopes?: string[];
      valid: boolean;
    };

    /** Pagination info */
    CursorPageInfo: {
      limit: number;
      count: number;
      nextCursor: string | null;
      hasPrevious: boolean;
      hasNext: boolean;
      total: number | null;
    };
  };
}
export interface operations {}
export interface webhooks {}
export type $defs = Record<string, never>;
