#!/usr/bin/env tsx
/**
 * scripts/generate-api-types.ts
 *
 * Fetches the OpenAPI spec from the backend and generates a TypeScript
 * types file at src/app/types/api.generated.ts using openapi-typescript.
 *
 * Usage (with backend running):
 *   npm run generate:api-types
 *
 * The generated file is committed so CI does not need a live backend.
 * Re-run this script whenever the backend API schema changes.
 *
 * Options (env vars):
 *   OPENAPI_SPEC_URL  – URL of the OpenAPI JSON spec.
 *                       Default: http://localhost:3001/docs.json
 *   OPENAPI_SPEC_FILE – Local file path to use instead of a URL.
 *                       Takes priority over OPENAPI_SPEC_URL.
 *
 * Related: validate:api-contract checks for breaking drift between the
 * generated types and the live spec.
 */

import openapiTS, { astToString } from "openapi-typescript";
import * as fs from "fs";
import * as path from "path";
import * as url from "url";

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const OUT_PATH = path.resolve(__dirname, "../src/app/types/api.generated.ts");
const SPEC_URL = process.env.OPENAPI_SPEC_URL ?? "http://localhost:3001/docs.json";
const SPEC_FILE = process.env.OPENAPI_SPEC_FILE;

const BANNER = `// GENERATED FILE — do not edit by hand.
//
// Generated by scripts/generate-api-types.ts from the backend OpenAPI spec.
// Re-run \`npm run generate:api-types\` after API schema changes.
//
// Import API types in application code via:
//   import type { ApiTypes } from "@/app/types";
//
// See docs/ENVIRONMENT.md and src/app/types/index.ts for usage details.

/* eslint-disable */
// prettier-ignore
`;

async function main() {
  console.log("[generate:api-types] Starting type generation…");

  let ast;

  if (SPEC_FILE) {
    console.log(`[generate:api-types] Reading spec from file: ${SPEC_FILE}`);
    const raw = fs.readFileSync(path.resolve(SPEC_FILE), "utf8");
    const specObject = JSON.parse(raw);
    ast = await openapiTS(specObject);
  } else {
    console.log(`[generate:api-types] Fetching spec from: ${SPEC_URL}`);
    try {
      const res = await fetch(SPEC_URL);
      if (!res.ok) {
        throw new Error(`HTTP ${res.status} ${res.statusText}`);
      }
      const specObject = await res.json();
      ast = await openapiTS(specObject);
    } catch (err) {
      console.error(
        `[generate:api-types] Failed to fetch spec from ${SPEC_URL}:`,
        err instanceof Error ? err.message : err,
      );
      console.error(
        "[generate:api-types] Make sure the backend is running, or set OPENAPI_SPEC_FILE to a local spec.",
      );
      process.exit(1);
    }
  }

  const typesString = astToString(ast);
  const output = BANNER + typesString;

  // Ensure the output directory exists
  fs.mkdirSync(path.dirname(OUT_PATH), { recursive: true });
  fs.writeFileSync(OUT_PATH, output, "utf8");

  console.log(`[generate:api-types] ✓ Written to ${OUT_PATH}`);
  console.log(
    `[generate:api-types] Commit the updated file so CI can import it without a live backend.`,
  );
}

main().catch((err) => {
  console.error("[generate:api-types] Unexpected error:", err);
  process.exit(1);
});
